version: "3.8"

services:
  connections-db:
    image: neo4j
    container_name: connections-db
    environment:
      - NEO4J_AUTH=neo4j/password  # Set your username and password
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    volumes:
      - connections-db-data:/data  # Persist data
    networks:
      - linkedin-network

  discovery-server:
    image: vishaltiwari95/linkedin-app/discovery-server
    container_name: discovery-server
    networks:
      - linkedin-network
    ports:
      - "8761:8761"

  connections-service:
    image: vishaltiwari95/linkedin-app/connection-service
    container_name: connections-service
    networks:
      - linkedin-network
    depends_on:
      - discovery-server
      - connections-db

  api-gateway:
    image: vishaltiwari95/linkedin-app/api-gateway
    container_name: api-gateway
    networks:
      - linkedin-network
    depends_on:
      - discovery-server

networks:
  linkedin-network:

volumes:
  connections-db-data: