apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4.39-community
        resources:
          limits:
            cpu: "200m"
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 600Mi
        ports:
        - containerPort: 7687 # Bolt
        env:
        - name: NEO4J_AUTH
          value: "neo4j/password" # Change as per your setup
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "512M"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "2G"
        - name: NEO4J_dbms_default__listen__address
          value: "0.0.0.0"
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
  volumeClaimTemplates:
  - metadata:
      name: neo4j-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: neo4j-logs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  clusterIP: None 
  ports:
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j
