apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: vishaltiwari95/linkedin-app-user-service
        imagePullPolicy: Always
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          # - name: DB_USER
          #   value: user
          # - name: DB_PASSWORD
          #   value: password
          # - name: DB_SERVICE
          #   value: user-db
          # - name: DB_NAME
          #   value: ms_userDB
        ports:
        - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 9020

  
