server:
  port: 9050
  servlet:
    context-path: /uploads

spring:
  application:
    name: uploader-service


cloudinary:
  cloud-name: dpszatzhb
  api-key: 672992884444429
  api-secret: QcWqXsXOO7PNcBXUANgHh8cOU60


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
